import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  IsObject,
} from 'class-validator';
import { UserEventType } from '@prisma/client';

export class TrackEventDto {
  @IsEnum(UserEventType)
  eventType!: UserEventType;

  // Opaque session ID generated by the client (UUID v4)
  @IsString()
  @MaxLength(64)
  sessionId!: string;

  // SHA256 of device fingerprint — computed client-side, never raw fingerprint
  @IsOptional()
  @IsString()
  @MaxLength(64)
  deviceId?: string;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  entityType?: string;

  @IsOptional()
  @IsString()
  @MaxLength(64)
  entityId?: string;

  // Freeform metadata — size-capped to prevent abuse
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;

  // Platform: 'ios' | 'android' | 'web'
  @IsOptional()
  @IsString()
  @MaxLength(16)
  platform?: string;
}
